-- Last modification date: 2016-08-20 13:07:27.408

-- Table: Client
-- number clients: 100
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (1,"Fermentum Metus PC","Ap #897-4752 Vivamus St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (2,"Pellentesque Ltd","445-260 Vivamus St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (3,"Egestas Aliquam Fringilla LLP","Ap #334-8786 Bibendum. Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (4,"Vel Turpis Aliquam LLP","Ap #718-2581 Et Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (5,"Orci Phasellus Dapibus Industries","423-5973 Sed Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (6,"Nonummy Ipsum Non Consulting","Ap #395-8885 Fringilla Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (7,"Ipsum Leo Elementum Ltd","535-1877 Duis Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (8,"Dui Fusce Inc.","5279 Cum Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (9,"Dui Suspendisse Industries","1736 Diam. Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (10,"Aenean Eget Corp.","P.O. Box 179, 8849 Sit Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (11,"Eu Ltd","973-8627 Cum Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (12,"Sed Consulting","2370 Ac Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (13,"Sodales Incorporated","4901 Tristique Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (14,"Habitant Company","P.O. Box 737, 1722 Ac Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (15,"Non Magna Corp.","129-1534 A, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (16,"Molestie Dapibus Ligula Associates","138-1533 Vivamus Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (17,"Tincidunt Neque Industries","608-8278 Magnis Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (18,"Posuere Cubilia LLP","7159 Malesuada St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (19,"Conubia Nostra Per Inc.","184-7162 Donec Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (20,"Luctus Ut Pellentesque Consulting","Ap #825-986 Aliquet, Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (21,"Sit Amet Corp.","P.O. Box 206, 3316 Dapibus Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (22,"Arcu Sed Et LLP","P.O. Box 132, 1051 Sit Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (23,"Euismod Corp.","Ap #388-9202 Erat, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (24,"Integer In LLC","P.O. Box 820, 7922 Eget St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (25,"Ut Industries","278-3371 Ante. Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (26,"Augue Consulting","854-7215 Suspendisse Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (27,"Nunc Quis Inc.","P.O. Box 402, 2594 Orci, Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (28,"Velit Industries","P.O. Box 533, 4833 At, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (29,"Praesent PC","2207 Dui. Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (30,"Ante Dictum LLC","5876 Orci Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (31,"Eget Institute","P.O. Box 822, 1473 Quam, Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (32,"Eu Tempor Erat LLC","Ap #619-648 Vel Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (33,"Et Malesuada Fames Institute","5883 Gravida Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (34,"Maecenas LLP","P.O. Box 512, 3479 Nulla Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (35,"Natoque Penatibus Inc.","2092 Eget Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (36,"Quis Urna Institute","P.O. Box 725, 3558 Aenean Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (37,"Mus Corp.","Ap #618-5283 Convallis, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (38,"Posuere Cubilia Curae; Industries","P.O. Box 225, 3098 Pede Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (39,"Amet Corporation","P.O. Box 363, 7501 Justo Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (40,"In Faucibus Orci Consulting","P.O. Box 863, 7194 Enim. Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (41,"Malesuada Corp.","232-6582 Dolor, Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (42,"Suspendisse Associates","2299 Ac Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (43,"Ipsum Dolor Sit Company","Ap #275-8860 Ut, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (44,"Lectus Quis Industries","Ap #402-2891 Elit Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (45,"Varius Nam Corporation","P.O. Box 282, 6085 Aliquam, Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (46,"Eget Odio Associates","3688 In Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (47,"Rutrum Industries","8592 Congue St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (48,"Aliquet Odio Etiam Inc.","P.O. Box 862, 6397 Sit St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (49,"Dolor Institute","2479 Diam Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (50,"Quisque Purus Sapien Inc.","P.O. Box 956, 5709 Dictum Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (51,"Erat Neque Ltd","P.O. Box 988, 5467 Nulla Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (52,"Sit Foundation","P.O. Box 528, 296 Mauris. Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (53,"Proin Corporation","Ap #717-9669 Mauris Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (54,"Odio A Purus Limited","Ap #774-8664 At Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (55,"Sit Amet Consulting","4854 Ipsum. Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (56,"Eget Ltd","350-7165 Curabitur Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (57,"Primis In LLP","301-4863 Tempor Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (58,"Amet Ornare Lectus Company","894 Scelerisque Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (59,"Augue Porttitor Interdum Institute","Ap #514-6494 Eu Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (60,"Feugiat Non Lobortis Corp.","500-5705 Convallis Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (61,"Donec Corp.","7559 Nam Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (62,"Ullamcorper Viverra Maecenas Institute","P.O. Box 953, 5804 Lacus St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (63,"Arcu Nunc Mauris LLC","Ap #162-5540 Ornare. Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (64,"Aliquam Consulting","P.O. Box 110, 2128 Maecenas St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (65,"Vel Pede Company","538-2030 Accumsan St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (66,"Ut Corporation","790-2944 Erat. Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (67,"Dui Industries","880-1688 Est Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (68,"Vestibulum Ut LLP","601-7578 Nibh. Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (69,"Aliquam Erat Volutpat Foundation","547 Dui. St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (70,"Ornare Placerat Orci Foundation","906-8909 Dolor. St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (71,"Aenean LLP","P.O. Box 222, 9049 Fringilla Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (72,"Sodales Mauris Blandit Ltd","3349 Nec St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (73,"Posuere Corp.","353 Rhoncus St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (74,"Mi Associates","P.O. Box 584, 1931 Dictum. Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (75,"Quam Elementum At Inc.","5731 Amet Road");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (76,"Semper Egestas Limited","6378 Id, Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (77,"Montes Nascetur Ridiculus Foundation","P.O. Box 177, 6640 Gravida Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (78,"Enim Diam Vel PC","Ap #196-2282 Donec St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (79,"Arcu Foundation","P.O. Box 551, 9958 Blandit Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (80,"Ullamcorper Duis Incorporated","P.O. Box 320, 6698 Erat Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (81,"Vitae Mauris Corporation","P.O. Box 195, 4726 Pede, St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (82,"Nisi Cum Sociis Foundation","211-2083 Lectus. Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (83,"Nunc Company","335-4823 Leo Ave");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (84,"Sem Egestas Blandit Consulting","925-5364 At Street");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (85,"Nec Diam Duis Institute","P.O. Box 589, 3678 Placerat. Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (86,"Lacinia LLC","4603 Rutrum Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (87,"Aenean Eget Magna Corp.","Ap #830-4357 Mi Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (88,"Est LLP","Ap #323-7049 Pede. Av.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (89,"Suspendisse Foundation","Ap #769-4277 Eget St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (90,"Feugiat Company","Ap #249-3434 Lobortis, Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (91,"Mauris Erat Foundation","530-7791 Fringilla Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (92,"Sed Diam Incorporated","Ap #968-1211 Faucibus. Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (93,"In Incorporated","Ap #506-1347 Rhoncus St.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (94,"Arcu LLC","P.O. Box 233, 1580 Pede. Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (95,"In Cursus Et Ltd","Ap #119-9086 Et Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (96,"Mauris Quis Incorporated","1405 Cras Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (97,"Odio Limited","Ap #226-5191 Tristique Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (98,"Eu Tellus Institute","158-6226 Ut, Rd.");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (99,"Risus Morbi Incorporated","5181 Ridiculus Avenue");
INSERT INTO `Client` (`id`,`client_name`,`client_address`) VALUES (100,"Turpis Non Enim Institute","543-9292 Amet Av.");
