-- Last modification date: 2016-08-20 13:07:27.408

-- Table: Item
-- number type: 200

insert into item (id, item_name, type_id, shelftime_id) values (1, 'eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 3, 8);
insert into item (id, item_name, type_id, shelftime_id) values (2, 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (3, 'erat curabitur gravida nisi at nibh', 9, 8);
insert into item (id, item_name, type_id, shelftime_id) values (4, 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (5, 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 7, 1);
insert into item (id, item_name, type_id, shelftime_id) values (6, 'sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue', 10, 8);
insert into item (id, item_name, type_id, shelftime_id) values (7, 'malesuada in imperdiet et commodo vulputate justo in blandit ultrices', 5, 2);
insert into item (id, item_name, type_id, shelftime_id) values (8, 'magna bibendum imperdiet nullam orci pede venenatis non', 1, 7);
insert into item (id, item_name, type_id, shelftime_id) values (9, 'lacus curabitur at ipsum ac', 4, 6);
insert into item (id, item_name, type_id, shelftime_id) values (10, 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc', 6, 5);
insert into item (id, item_name, type_id, shelftime_id) values (11, 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 6, 4);
insert into item (id, item_name, type_id, shelftime_id) values (12, 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante', 3, 5);
insert into item (id, item_name, type_id, shelftime_id) values (13, 'luctus et ultrices posuere cubilia curae nulla dapibus dolor vel', 10, 7);
insert into item (id, item_name, type_id, shelftime_id) values (14, 'congue vivamus metus arcu adipiscing molestie hendrerit at', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (15, 'accumsan felis ut at dolor quis odio consequat varius integer', 5, 4);
insert into item (id, item_name, type_id, shelftime_id) values (16, 'ultrices erat tortor sollicitudin mi', 7, 5);
insert into item (id, item_name, type_id, shelftime_id) values (17, 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 10, 1);
insert into item (id, item_name, type_id, shelftime_id) values (18, 'rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia', 1, 8);
insert into item (id, item_name, type_id, shelftime_id) values (19, 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra', 4, 7);
insert into item (id, item_name, type_id, shelftime_id) values (20, 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 6, 7);
insert into item (id, item_name, type_id, shelftime_id) values (21, 'metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero', 3, 8);
insert into item (id, item_name, type_id, shelftime_id) values (22, 'ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 5, 4);
insert into item (id, item_name, type_id, shelftime_id) values (23, 'nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum', 2, 2);
insert into item (id, item_name, type_id, shelftime_id) values (24, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 7, 5);
insert into item (id, item_name, type_id, shelftime_id) values (25, 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem', 7, 5);
insert into item (id, item_name, type_id, shelftime_id) values (26, 'congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget', 7, 1);
insert into item (id, item_name, type_id, shelftime_id) values (27, 'in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 3, 5);
insert into item (id, item_name, type_id, shelftime_id) values (28, 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 4, 1);
insert into item (id, item_name, type_id, shelftime_id) values (29, 'convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 2, 5);
insert into item (id, item_name, type_id, shelftime_id) values (30, 'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes', 1, 3);
insert into item (id, item_name, type_id, shelftime_id) values (31, 'volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 2, 6);
insert into item (id, item_name, type_id, shelftime_id) values (32, 'magna vulputate luctus cum sociis natoque penatibus et', 3, 6);
insert into item (id, item_name, type_id, shelftime_id) values (33, 'accumsan felis ut at dolor quis odio consequat varius integer ac', 4, 8);
insert into item (id, item_name, type_id, shelftime_id) values (34, 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 10, 7);
insert into item (id, item_name, type_id, shelftime_id) values (35, 'quam nec dui luctus rutrum nulla tellus', 2, 4);
insert into item (id, item_name, type_id, shelftime_id) values (36, 'quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 2, 8);
insert into item (id, item_name, type_id, shelftime_id) values (37, 'erat nulla tempus vivamus in felis eu sapien cursus', 6, 5);
insert into item (id, item_name, type_id, shelftime_id) values (38, 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 10, 3);
insert into item (id, item_name, type_id, shelftime_id) values (39, 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 9, 2);
insert into item (id, item_name, type_id, shelftime_id) values (40, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae', 4, 8);
insert into item (id, item_name, type_id, shelftime_id) values (41, 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis', 10, 3);
insert into item (id, item_name, type_id, shelftime_id) values (42, 'diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 6, 8);
insert into item (id, item_name, type_id, shelftime_id) values (43, 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis', 3, 6);
insert into item (id, item_name, type_id, shelftime_id) values (44, 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus', 5, 3);
insert into item (id, item_name, type_id, shelftime_id) values (45, 'amet eros suspendisse accumsan tortor quis turpis sed', 4, 7);
insert into item (id, item_name, type_id, shelftime_id) values (46, 'neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum', 6, 6);
insert into item (id, item_name, type_id, shelftime_id) values (47, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam', 10, 5);
insert into item (id, item_name, type_id, shelftime_id) values (48, 'etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut', 7, 3);
insert into item (id, item_name, type_id, shelftime_id) values (49, 'neque libero convallis eget eleifend luctus ultricies eu', 3, 7);
insert into item (id, item_name, type_id, shelftime_id) values (50, 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 1, 8);
insert into item (id, item_name, type_id, shelftime_id) values (51, 'sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 9, 2);
insert into item (id, item_name, type_id, shelftime_id) values (52, 'elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 5, 5);
insert into item (id, item_name, type_id, shelftime_id) values (53, 'habitasse platea dictumst morbi vestibulum velit id', 6, 6);
insert into item (id, item_name, type_id, shelftime_id) values (54, 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 1, 3);
insert into item (id, item_name, type_id, shelftime_id) values (55, 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio', 2, 2);
insert into item (id, item_name, type_id, shelftime_id) values (56, 'euismod scelerisque quam turpis adipiscing', 8, 8);
insert into item (id, item_name, type_id, shelftime_id) values (57, 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 8, 3);
insert into item (id, item_name, type_id, shelftime_id) values (58, 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 10, 8);
insert into item (id, item_name, type_id, shelftime_id) values (59, 'sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 4, 4);
insert into item (id, item_name, type_id, shelftime_id) values (60, 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis', 9, 2);
insert into item (id, item_name, type_id, shelftime_id) values (61, 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc', 1, 1);
insert into item (id, item_name, type_id, shelftime_id) values (62, 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', 8, 7);
insert into item (id, item_name, type_id, shelftime_id) values (63, 'dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 7, 4);
insert into item (id, item_name, type_id, shelftime_id) values (64, 'nibh ligula nec sem duis aliquam convallis nunc proin', 10, 7);
insert into item (id, item_name, type_id, shelftime_id) values (65, 'phasellus in felis donec semper sapien a libero nam', 4, 5);
insert into item (id, item_name, type_id, shelftime_id) values (66, 'venenatis non sodales sed tincidunt', 6, 6);
insert into item (id, item_name, type_id, shelftime_id) values (67, 'sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et', 1, 5);
insert into item (id, item_name, type_id, shelftime_id) values (68, 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed', 9, 8);
insert into item (id, item_name, type_id, shelftime_id) values (69, 'pulvinar sed nisl nunc rhoncus dui', 10, 3);
insert into item (id, item_name, type_id, shelftime_id) values (70, 'nulla mollis molestie lorem quisque ut erat curabitur gravida', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (71, 'euismod scelerisque quam turpis adipiscing lorem vitae mattis', 9, 1);
insert into item (id, item_name, type_id, shelftime_id) values (72, 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (73, 'libero nam dui proin leo odio porttitor', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (74, 'eget semper rutrum nulla nunc purus phasellus in felis donec semper', 6, 2);
insert into item (id, item_name, type_id, shelftime_id) values (75, 'duis bibendum felis sed interdum venenatis turpis', 2, 3);
insert into item (id, item_name, type_id, shelftime_id) values (76, 'nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo', 8, 5);
insert into item (id, item_name, type_id, shelftime_id) values (77, 'habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 10, 5);
insert into item (id, item_name, type_id, shelftime_id) values (78, 'tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 9, 2);
insert into item (id, item_name, type_id, shelftime_id) values (79, 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', 7, 3);
insert into item (id, item_name, type_id, shelftime_id) values (80, 'rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo', 4, 3);
insert into item (id, item_name, type_id, shelftime_id) values (81, 'leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id', 3, 7);
insert into item (id, item_name, type_id, shelftime_id) values (82, 'est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 6, 7);
insert into item (id, item_name, type_id, shelftime_id) values (83, 'venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 6, 2);
insert into item (id, item_name, type_id, shelftime_id) values (84, 'velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit', 3, 4);
insert into item (id, item_name, type_id, shelftime_id) values (85, 'duis ac nibh fusce lacus purus aliquet', 2, 5);
insert into item (id, item_name, type_id, shelftime_id) values (86, 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper', 1, 7);
insert into item (id, item_name, type_id, shelftime_id) values (87, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 3, 6);
insert into item (id, item_name, type_id, shelftime_id) values (88, 'placerat praesent blandit nam nulla integer pede justo lacinia eget', 6, 4);
insert into item (id, item_name, type_id, shelftime_id) values (89, 'metus vitae ipsum aliquam non mauris morbi', 2, 5);
insert into item (id, item_name, type_id, shelftime_id) values (90, 'in sagittis dui vel nisl duis ac nibh fusce', 2, 6);
insert into item (id, item_name, type_id, shelftime_id) values (91, 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 5, 6);
insert into item (id, item_name, type_id, shelftime_id) values (92, 'amet consectetuer adipiscing elit proin interdum mauris non ligula', 4, 7);
insert into item (id, item_name, type_id, shelftime_id) values (93, 'ante vel ipsum praesent blandit lacinia erat vestibulum sed', 2, 1);
insert into item (id, item_name, type_id, shelftime_id) values (94, 'luctus tincidunt nulla mollis molestie lorem quisque ut erat', 5, 7);
insert into item (id, item_name, type_id, shelftime_id) values (95, 'maecenas tristique est et tempus semper est quam pharetra magna ac', 3, 7);
insert into item (id, item_name, type_id, shelftime_id) values (96, 'proin eu mi nulla ac enim in', 1, 2);
insert into item (id, item_name, type_id, shelftime_id) values (97, 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam', 6, 3);
insert into item (id, item_name, type_id, shelftime_id) values (98, 'eu mi nulla ac enim in tempor turpis nec', 9, 2);
insert into item (id, item_name, type_id, shelftime_id) values (99, 'fusce congue diam id ornare', 2, 4);
insert into item (id, item_name, type_id, shelftime_id) values (100, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (101, 'sociis natoque penatibus et magnis dis parturient', 2, 3);
insert into item (id, item_name, type_id, shelftime_id) values (102, 'odio cras mi pede malesuada in', 9, 7);
insert into item (id, item_name, type_id, shelftime_id) values (103, 'magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus', 4, 2);
insert into item (id, item_name, type_id, shelftime_id) values (104, 'vehicula consequat morbi a ipsum integer', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (105, 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 2, 5);
insert into item (id, item_name, type_id, shelftime_id) values (106, 'interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in', 9, 7);
insert into item (id, item_name, type_id, shelftime_id) values (107, 'eleifend quam a odio in hac habitasse platea dictumst maecenas ut', 8, 5);
insert into item (id, item_name, type_id, shelftime_id) values (108, 'posuere cubilia curae mauris viverra diam vitae quam suspendisse', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (109, 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio', 8, 6);
insert into item (id, item_name, type_id, shelftime_id) values (110, 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 3, 4);
insert into item (id, item_name, type_id, shelftime_id) values (111, 'sem duis aliquam convallis nunc proin at turpis', 4, 8);
insert into item (id, item_name, type_id, shelftime_id) values (112, 'nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', 8, 6);
insert into item (id, item_name, type_id, shelftime_id) values (113, 'nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (114, 'ut erat id mauris vulputate elementum nullam varius nulla facilisi', 3, 2);
insert into item (id, item_name, type_id, shelftime_id) values (115, 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 2, 1);
insert into item (id, item_name, type_id, shelftime_id) values (116, 'in felis donec semper sapien a libero nam', 9, 4);
insert into item (id, item_name, type_id, shelftime_id) values (117, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl', 2, 7);
insert into item (id, item_name, type_id, shelftime_id) values (118, 'varius integer ac leo pellentesque ultrices mattis odio donec vitae', 9, 5);
insert into item (id, item_name, type_id, shelftime_id) values (119, 'eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum', 1, 6);
insert into item (id, item_name, type_id, shelftime_id) values (120, 'scelerisque quam turpis adipiscing lorem vitae mattis', 5, 8);
insert into item (id, item_name, type_id, shelftime_id) values (121, 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu', 6, 2);
insert into item (id, item_name, type_id, shelftime_id) values (122, 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet', 2, 8);
insert into item (id, item_name, type_id, shelftime_id) values (123, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 3, 8);
insert into item (id, item_name, type_id, shelftime_id) values (124, 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 4, 2);
insert into item (id, item_name, type_id, shelftime_id) values (125, 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 6, 1);
insert into item (id, item_name, type_id, shelftime_id) values (126, 'non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel', 3, 5);
insert into item (id, item_name, type_id, shelftime_id) values (127, 'aliquam lacus morbi quis tortor id nulla ultrices', 5, 1);
insert into item (id, item_name, type_id, shelftime_id) values (128, 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 9, 4);
insert into item (id, item_name, type_id, shelftime_id) values (129, 'luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec', 5, 7);
insert into item (id, item_name, type_id, shelftime_id) values (130, 'dolor morbi vel lectus in quam', 2, 8);
insert into item (id, item_name, type_id, shelftime_id) values (131, 'duis bibendum morbi non quam nec dui luctus', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (132, 'diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci', 8, 5);
insert into item (id, item_name, type_id, shelftime_id) values (133, 'felis donec semper sapien a libero nam dui', 3, 6);
insert into item (id, item_name, type_id, shelftime_id) values (134, 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus', 6, 1);
insert into item (id, item_name, type_id, shelftime_id) values (135, 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 7, 8);
insert into item (id, item_name, type_id, shelftime_id) values (136, 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', 5, 3);
insert into item (id, item_name, type_id, shelftime_id) values (137, 'turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 7, 3);
insert into item (id, item_name, type_id, shelftime_id) values (138, 'proin interdum mauris non ligula pellentesque ultrices phasellus id', 10, 5);
insert into item (id, item_name, type_id, shelftime_id) values (139, 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', 5, 7);
insert into item (id, item_name, type_id, shelftime_id) values (140, 'quam turpis adipiscing lorem vitae mattis nibh', 3, 8);
insert into item (id, item_name, type_id, shelftime_id) values (141, 'nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id', 10, 7);
insert into item (id, item_name, type_id, shelftime_id) values (142, 'sociis natoque penatibus et magnis', 5, 6);
insert into item (id, item_name, type_id, shelftime_id) values (143, 'in hac habitasse platea dictumst maecenas ut massa quis augue', 10, 5);
insert into item (id, item_name, type_id, shelftime_id) values (144, 'fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in', 2, 5);
insert into item (id, item_name, type_id, shelftime_id) values (145, 'nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 1, 2);
insert into item (id, item_name, type_id, shelftime_id) values (146, 'sapien quis libero nullam sit amet turpis elementum ligula', 5, 5);
insert into item (id, item_name, type_id, shelftime_id) values (147, 'venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 8, 4);
insert into item (id, item_name, type_id, shelftime_id) values (148, 'morbi non lectus aliquam sit amet diam in magna bibendum', 3, 3);
insert into item (id, item_name, type_id, shelftime_id) values (149, 'mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus', 5, 3);
insert into item (id, item_name, type_id, shelftime_id) values (150, 'viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla', 9, 1);
insert into item (id, item_name, type_id, shelftime_id) values (151, 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 8, 7);
insert into item (id, item_name, type_id, shelftime_id) values (152, 'a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 7, 1);
insert into item (id, item_name, type_id, shelftime_id) values (153, 'phasellus sit amet erat nulla tempus vivamus in felis', 10, 6);
insert into item (id, item_name, type_id, shelftime_id) values (154, 'consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 3, 8);
insert into item (id, item_name, type_id, shelftime_id) values (155, 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus', 6, 8);
insert into item (id, item_name, type_id, shelftime_id) values (156, 'enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 7, 3);
insert into item (id, item_name, type_id, shelftime_id) values (157, 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus', 8, 4);
insert into item (id, item_name, type_id, shelftime_id) values (158, 'interdum mauris ullamcorper purus sit amet nulla', 5, 8);
insert into item (id, item_name, type_id, shelftime_id) values (159, 'enim in tempor turpis nec euismod scelerisque quam', 9, 1);
insert into item (id, item_name, type_id, shelftime_id) values (160, 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 8, 7);
insert into item (id, item_name, type_id, shelftime_id) values (161, 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id', 9, 8);
insert into item (id, item_name, type_id, shelftime_id) values (162, 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', 4, 5);
insert into item (id, item_name, type_id, shelftime_id) values (163, 'velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 10, 3);
insert into item (id, item_name, type_id, shelftime_id) values (164, 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu', 7, 1);
insert into item (id, item_name, type_id, shelftime_id) values (165, 'blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 8, 5);
insert into item (id, item_name, type_id, shelftime_id) values (166, 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', 6, 3);
insert into item (id, item_name, type_id, shelftime_id) values (167, 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor', 1, 5);
insert into item (id, item_name, type_id, shelftime_id) values (168, 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet', 1, 8);
insert into item (id, item_name, type_id, shelftime_id) values (169, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at', 1, 3);
insert into item (id, item_name, type_id, shelftime_id) values (170, 'accumsan odio curabitur convallis duis consequat dui nec nisi', 8, 6);
insert into item (id, item_name, type_id, shelftime_id) values (171, 'donec dapibus duis at velit eu est congue elementum in hac', 7, 3);
insert into item (id, item_name, type_id, shelftime_id) values (172, 'vestibulum ac est lacinia nisi venenatis tristique fusce congue', 9, 1);
insert into item (id, item_name, type_id, shelftime_id) values (173, 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 2, 7);
insert into item (id, item_name, type_id, shelftime_id) values (174, 'magna vulputate luctus cum sociis natoque penatibus', 5, 2);
insert into item (id, item_name, type_id, shelftime_id) values (175, 'mauris enim leo rhoncus sed vestibulum sit', 8, 7);
insert into item (id, item_name, type_id, shelftime_id) values (176, 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem', 1, 4);
insert into item (id, item_name, type_id, shelftime_id) values (177, 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat', 10, 3);
insert into item (id, item_name, type_id, shelftime_id) values (178, 'habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 4, 3);
insert into item (id, item_name, type_id, shelftime_id) values (179, 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 4, 4);
insert into item (id, item_name, type_id, shelftime_id) values (180, 'augue quam sollicitudin vitae consectetuer eget rutrum at', 1, 7);
insert into item (id, item_name, type_id, shelftime_id) values (181, 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 10, 5);
insert into item (id, item_name, type_id, shelftime_id) values (182, 'volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet', 6, 5);
insert into item (id, item_name, type_id, shelftime_id) values (183, 'sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', 5, 2);
insert into item (id, item_name, type_id, shelftime_id) values (184, 'odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', 6, 1);
insert into item (id, item_name, type_id, shelftime_id) values (185, 'mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus', 6, 6);
insert into item (id, item_name, type_id, shelftime_id) values (186, 'fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat', 8, 6);
insert into item (id, item_name, type_id, shelftime_id) values (187, 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 10, 7);
insert into item (id, item_name, type_id, shelftime_id) values (188, 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien', 3, 6);
insert into item (id, item_name, type_id, shelftime_id) values (189, 'nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut', 10, 6);
insert into item (id, item_name, type_id, shelftime_id) values (190, 'in felis donec semper sapien a libero nam dui proin leo odio porttitor', 1, 6);
insert into item (id, item_name, type_id, shelftime_id) values (191, 'in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat', 2, 7);
insert into item (id, item_name, type_id, shelftime_id) values (192, 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras', 4, 1);
insert into item (id, item_name, type_id, shelftime_id) values (193, 'eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc', 2, 7);
insert into item (id, item_name, type_id, shelftime_id) values (194, 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in', 3, 7);
insert into item (id, item_name, type_id, shelftime_id) values (195, 'elit proin risus praesent lectus vestibulum quam sapien varius', 7, 6);
insert into item (id, item_name, type_id, shelftime_id) values (196, 'dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis', 10, 8);
insert into item (id, item_name, type_id, shelftime_id) values (197, 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio', 7, 1);
insert into item (id, item_name, type_id, shelftime_id) values (198, 'massa id nisl venenatis lacinia aenean sit amet justo morbi', 9, 5);
insert into item (id, item_name, type_id, shelftime_id) values (199, 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 9, 3);
insert into item (id, item_name, type_id, shelftime_id) values (200, 'quis tortor id nulla ultrices aliquet maecenas leo', 10, 6);
